[package]
name = "openapi_diff"
version = "0.1.0"
edition = "2021"

[dependencies]
oas3 = { version = "0.19.0", features = ["yaml-spec"] }
serde_json = "1.0"
tera = "1.20"
serde = { version = "1.0", features = ["derive"] }
open = "5.0"
clap = { version = "4.5", features = ["derive"] }
